#!/bin/bash
flag=0
for i in $(find . -type f ! -path "*/*.egg-info/*"\
    ! -path "./.*"\
    ! -path "*.min.*"\
    ! -path "*.svg" -exec grep -Iq . {} \; -and -print); do
    if [ "$(tail -c 1 $i)" != "" ]; then
        echo "$i needs newline at the end"
        flag=1
    fi
done
if [ $flag -eq 1 ]; then
    echo "Add newline at the end of above files"
    echo "You can use this script to do this automatically"
    echo "https://github.com/unsuitable001/usnippet/blob/master/addendline.sh"
    exit 1
fi
